name: CI

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test github-changelog-generator
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
    repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1.29
      - name: Run github-changelog-generator
        uses: ./
        with:
          output: 'HISTORY.md'
      - name: Run github-changelog-generator with PAT token.
        uses: ./
        with:
          output: 'HISTORY.md'
          token: ${{ secrets.PAT_TOKEN }}
